FROM ubuntu:18.04

MAINTAINER "Shahrokh Nabavi <info@nabavi.nl>"
LABEL Version="1.0" \
      Author="Shahrokh"

# Setting the following environment so that no question/dialog is asked during apt-get insta
ENV DEBIAN_FRONTEND="noninteractive"