#!/usr/bin/env bash

if [ $# -gt 0 ]; then

    if [ "$1" == "start" ]; then
        docker-compose up

    elif [ "$1" == "stop" ]; then
        docker-compose down

    elif [ "$1" == "composer" ] || [ "$1" == "comp" ]; then
        shift 1
        docker-compose exec web composer "$@"

    elif [ "$1" == "unit_test" ]; then
        shift 1
        docker-compose exec web ./vendor/bin/phpunit "$@"

    elif [ "$1" == "migrate" ]; then
        shift 1
        docker-compose exec web ./vendor/bin/doctrine-module "$@"

    elif [ "$1" == "npm" ]; then
        shift 1
        docker-compose run --rm node npm "$@"

    elif [ "$1" == "yarn" ]; then
        shift 1
        docker-compose run --rm node yarn "$@"

    elif [ "$1" == "gulp" ]; then
        shift 1
        docker-compose run --rm node ./node_modules/.bin/gulp "$@"

    elif [ "$1" == "zf2" ]; then
        shift 1
        docker-compose exec web composer create-project zendframework/skeleton-application . ^2.4

    elif [ "$1" == "zf" ]; then
        shift 1
        docker-compose exec web composer create-project zendframework/skeleton-application .

    else
        docker-compose "$@"
    fi

#    docker images
#    docker ps -a
#    docker build -t nari/wep -f ./docker/app/Dockerfile .
#    docker build -t nari/node -f ./docker/node/Dockerfile .
else
    docker-compose ps
fi
