<?= $this->doctype() ?>
<html lang="en">
<head>
    <base href="/admin">
    <meta charset="utf-8">
    <?php

    echo $this->headTitle('Angular');

    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

    echo $this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')]);
    ?>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu|Titillium+Web" rel="stylesheet">
</head>
<body>
<?= $this->content ?>
<?= $this->headScript()
    ->prependFile($this->basePath('/angular/main.js'))
    ->prependFile($this->basePath('/angular/polyfills.js'))
    ->prependFile($this->basePath('/angular/runtime.js'))
    ->prependFile($this->basePath('/angular/styles.js'))
    ->prependFile($this->basePath('/angular/vendor.js'));
?>
<?= $this->inlineScript() ?>
</body>
</html>
