<?php

$resetPasswordLink = $this->url(
    'user-api.rpc.confirm-email',
    [
        'email' => $email,
        'token' => $resetToken,
    ],
    ['force_canonical' => true]
);
?>
<h2>Hello <?= $fullname ?>,</h2>
<p>
    You requested to reset your password. To complete reset process please click following link, or
    copy and paste it in your browser address bar:
    <a href="<?= $resetPasswordLink ?>"><?= $resetPasswordLink; ?></a>
    <br/>
    If you didn't request this operation just ignore this email.
</p>
